### PR TITLE
BIR-26 Fix home button

### PR DESCRIPTION
**Pull request by Akayeshmantha**
Summary : issue fix for https://issues.openmrs.org/browse/BIR-26

Tests : Not applicable

Expected output :Home icon on the upper left right corner should redirect to the index page.

### CODE REVIEW

**Comment by Akayeshmantha** [comment]
@dkayiwa  this also the commit message is fixed but can't assign it btw will attach screen recording of this.

**Comment by dkayiwa** [comment]
Just hit the "Assign Issue" button.

**Comment by JudeNiroshan** [comment]
@dkayiwa Can we merge this?

**Comment by dkayiwa** [comment]
@JudeNiroshan did you take a look at my previous comment?

**Comment by Akayeshmantha** [comment]
Already assigned @dkayiwa

**Comment by dkayiwa** [comment]
@JudeNiroshan i have just given you permission to merge pull requests on this repository. Do you still need my help in merging this? 😊

**Comment by JudeNiroshan** [comment]
@dkayiwa Thank you very much! I think now I can take care of this module. 👍

**Comment by dkayiwa** [comment]
Oh yes you have earned that trust! 😊

**Comment by Akayeshmantha** [comment]
@JudeNiroshan congratz man

**Comment by Akayeshmantha** [comment]
@JudeNiroshan  @dkayiwa  can someone merge this.

**Comment by dkayiwa** [comment]
Over to you @JudeNiroshan  😊

**Pull request merged**
